# Generated by Django 5.2.4 on 2025-08-12 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_postimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='post_images/default.jpg', upload_to='post_images/'),
        ),
        migrations.DeleteModel(
            name='PostImage',
        ),
    ]
